name: vita_quest
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.6
  # For storing data locally. 
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.2
  # For theming.
  google_fonts: ^6.2.1
  # For image handling.
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  # For app deployment.
  flutter_native_splash: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  # For networking.
  dio: ^5.4.0
  # For state Management & Logic.
  flutter_bloc: ^8.1.3
  # For responsivity.
  flutter_screenutil: ^5.9.0
  # For dependency injection.
  get_it: ^7.6.7
  # For json operations handling.
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  # For generating code.
  build_runner: ^2.4.11
  # For more return types.
  dartz: ^0.10.1
  # For Loading styling.
  shimmer: ^3.0.0
  # For secured cahce.
  flutter_secure_storage: ^9.2.2
  # For onBoarding stepper.
  smooth_page_indicator: ^1.2.0+3
  # For implementing value based equality.
  equatable: ^2.0.5
  # For string-based path manipulation.
  path: ^1.9.0
  # For providing a calendar as a horizontal timeline.
  date_picker_timeline: ^1.2.6
  pinput: ^5.0.0
  # For adding a dashed border around any widget.
  dotted_border: ^2.1.0
  # For Firebase Core, enabling connecting to multiple Firebase apps. 
  firebase_core: ^2.24.2

# An extension for generating assets file located in helpers folder.
flutter_assets:
  assets_path: assets/
  output_path: lib/core/helpers/
  filename: app_images.dart
  field_prefix:

# For changing the application icon.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/svgs/
    - assets/fonts/cairo/

