// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBara8JdhKHn9doV3U459WrdxBZjVLokH8',
    appId: '1:1096763828788:web:5b71983267b729a800f861',
    messagingSenderId: '1096763828788',
    projectId: 'vitaquest',
    authDomain: 'vitaquest.firebaseapp.com',
    storageBucket: 'vitaquest.appspot.com',
    measurementId: 'G-V59WM7R33L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIEUnjoOlDzJ2Irsu1KdYAscCzeZacfSs',
    appId: '1:1096763828788:android:1128e553faf11cc500f861',
    messagingSenderId: '1096763828788',
    projectId: 'vitaquest',
    storageBucket: 'vitaquest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Jxy8RY2KGxVPcaToASW1jWgEuBBMApc',
    appId: '1:1096763828788:ios:4052bdcb4713d02900f861',
    messagingSenderId: '1096763828788',
    projectId: 'vitaquest',
    storageBucket: 'vitaquest.appspot.com',
    iosBundleId: 'com.VitaQuest.vitaQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Jxy8RY2KGxVPcaToASW1jWgEuBBMApc',
    appId: '1:1096763828788:ios:68b9a4cb4c8781b600f861',
    messagingSenderId: '1096763828788',
    projectId: 'vitaquest',
    storageBucket: 'vitaquest.appspot.com',
    iosBundleId: 'com.example.vitaQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBara8JdhKHn9doV3U459WrdxBZjVLokH8',
    appId: '1:1096763828788:web:5645ea2c3269655000f861',
    messagingSenderId: '1096763828788',
    projectId: 'vitaquest',
    authDomain: 'vitaquest.firebaseapp.com',
    storageBucket: 'vitaquest.appspot.com',
    measurementId: 'G-XM8QMYXP1W',
  );
}
